# -*- coding:utf-8 -*-

class Config:

    # 沙子中采样的权重
    SAND_RATIO = {"0_bk_bloodiness_human": 1,
             "1_bk_bomb_fire": 1,
             "2_bk_bomb_smoke": 1,
             "3_bk_bomb_vehicle": 1,
             "4_bk_bomb_self-burning": 1,
             "5_bk_beheaded_isis": 1,
             "6_bk_beheaded_decollation": 1,
             "7_bk_march_banner": 1,
             "8_bk_march_crowed": 1,
             "9_bk_fight_police": 1,
             "10_bk_fight_person": 1,
             "11_sen_character": 1,
             "12_sen_masked": 1,
             "13_sen_army": 1,
             "14_sen_scene_person": 1,
             "15_sen_anime_likely_bloodiness": 1,
             "16_sen_anime_likely_bomb": 1,
             "17_sen_Islamic_dress": 1,
             "18_abnormal_bloodiness_animal": 1,
             "19_abnormal_disaster-scene": 1,
             "20_abnormal_porn": 1,
             "21_normal_bloodiness_likely_anime": 1,
             "22_normal_fight_likely_sports": 1,
             "23_normal_fight_likely_box": 1,
             "24_normal_fight_likely_fencing": 1,
             "25_normal_fight_likely_judo": 1,
             "26_normal_fight_likely_bullfight": 1,
             "27_normal_fight_likely_ancient_war": 1,
             "28_normal_text_weibo": 1,
             "29_normal_text_chat": 1,
             "30_normal_bomb_likely_atom": 1,
             "31_normal_bomb_likely_rocket": 1,
             "32_normal_bomb_likely_sunrise": 1,
             "33_normal_bomb_likely_haze": 1,
             "34_normal_bomb_likely_candlelight": 1,
             "35_normal_bomb_likely_vehicles": 1,
             "36_normal_march_likely_crowed": 1,
             "37_normal_march_likely_troops": 1,
             "38_normal_march_likely_legal_banner": 1,
             "39_normal_march_likely_photo": 1,
             "40_normal_march_likely_aerial": 1,
             "41_normal_march_likely_animal_migration": 1,
             "42_normal_march_beach_crowed": 1,
             "43_normal_march_vocal_concert": 1,
             "44_normal_pron_likely_sexy": 1,
             "45_background_text": 1,
             "46_background_with_people": 1,
             "47_background_no_people": 1
             }
    # 池子中采样的权重
    POOL_RATIO = {"0_bk_bloodiness_human": 1,
                  "1_bk_bomb_fire": 1,
                  "2_bk_bomb_smoke": 1,
                  "3_bk_bomb_vehicle": 1,
                  "4_bk_bomb_self-burning": 1,
                  "5_bk_beheaded_isis": 1,
                  "6_bk_beheaded_decollation": 1,
                  "7_bk_march_banner": 1,
                  "8_bk_march_crowed": 1,
                  "9_bk_fight_police": 1,
                  "10_bk_fight_person": 1,
                  "11_sen_character": 1,
                  "12_sen_masked": 1,
                  "13_sen_army": 1,
                  "14_sen_scene_person": 1,
                  "15_sen_anime_likely_bloodiness": 1,
                  "16_sen_anime_likely_bomb": 1,
                  "17_sen_Islamic_dress": 1,
                  "18_abnormal_bloodiness_animal": 1,
                  "19_abnormal_disaster-scene": 1,
                  "20_abnormal_porn": 1,
                  "21_normal_bloodiness_likely_anime": 1,
                  "22_normal_fight_likely_sports": 1,
                  "23_normal_fight_likely_box": 1,
                  "24_normal_fight_likely_fencing": 1,
                  "25_normal_fight_likely_judo": 1,
                  "26_normal_fight_likely_bullfight": 1,
                  "27_normal_fight_likely_ancient_war": 1,
                  "28_normal_text_weibo": 1,
                  "29_normal_text_chat": 1,
                  "30_normal_bomb_likely_atom": 1,
                  "31_normal_bomb_likely_rocket": 1,
                  "32_normal_bomb_likely_sunrise": 1,
                  "33_normal_bomb_likely_haze": 1,
                  "34_normal_bomb_likely_candlelight": 1,
                  "35_normal_bomb_likely_vehicles": 1,
                  "36_normal_march_likely_crowed": 1,
                  "37_normal_march_likely_troops": 1,
                  "38_normal_march_likely_legal_banner": 1,
                  "39_normal_march_likely_photo": 1,
                  "40_normal_march_likely_aerial": 1,
                  "41_normal_march_likely_animal_migration": 1,
                  "42_normal_march_beach_crowed": 1,
                  "43_normal_march_vocal_concert": 1,
                  "44_normal_pron_likely_sexy": 1,
                  "45_background_text": 1,
                  "46_background_with_people": 1,
                  "47_background_no_people": 1
                  }
    CATEGORYS = ["0_bk_bloodiness_human",
                 "1_bk_bomb_fire",
                 "2_bk_bomb_smoke",
                 "3_bk_bomb_vehicle",
                 "4_bk_bomb_self-burning",
                 "5_bk_beheaded_isis",
                 "6_bk_beheaded_decollation",
                 "7_bk_march_banner",
                 "8_bk_march_crowed",
                 "9_bk_fight_police",
                 "10_bk_fight_person",
                 "11_sen_character",
                 "12_sen_masked",
                 "13_sen_army",
                 "14_sen_scene_person",
                 "15_sen_anime_likely_bloodiness",
                 "16_sen_anime_likely_bomb",
                 "17_sen_Islamic_dress",
                 "18_abnormal_bloodiness_animal",
                 "19_abnormal_disaster-scene",
                 "20_abnormal_porn",
                 "21_normal_bloodiness_likely_anime",
                 "22_normal_fight_likely_sports",
                 "23_normal_fight_likely_box",
                 "24_normal_fight_likely_fencing",
                 "25_normal_fight_likely_judo",
                 "26_normal_fight_likely_bullfight",
                 "27_normal_fight_likely_ancient_war",
                 "28_normal_text_weibo",
                 "29_normal_text_chat",
                 "30_normal_bomb_likely_atom",
                 "31_normal_bomb_likely_rocket",
                 "32_normal_bomb_likely_sunrise",
                 "33_normal_bomb_likely_haze",
                 "34_normal_bomb_likely_candlelight",
                 "35_normal_bomb_likely_vehicles",
                 "36_normal_march_likely_crowed",
                 "37_normal_march_likely_troops",
                 "38_normal_march_likely_legal_banner",
                 "39_normal_march_likely_photo",
                 "40_normal_march_likely_aerial",
                 "41_normal_march_likely_animal_migration",
                 "42_normal_march_beach_crowed",
                 "43_normal_march_vocal_concert",
                 "44_normal_pron_likely_sexy",
                 "45_background_text",
                 "46_background_with_people",
                 "47_background_no_people",
                 ]
    
